export { default as checkIfTestSlicesEqual100 } from './checkIfTestSlicesEqual100'
export { default as getStoredTests } from './getStoredTests'
export { default as setStoredTests } from './setStoredTests'
export { default as getTestSlice } from './getTestSlice'
export { default as isFloat } from './isFloat'
